name = "Darks Fast Pack"
author = "darksaid98"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2fc75f65f87f13a1e3dabcf857c632f209a423e7b4ff936f9ec8482f4c7bcf06"

[versions]
fabric = "0.15.3"
minecraft = "1.20.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1", "1.20.2"]
