name = "Optim"
author = "darksaid98"
version = "1.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f8fe61aeb8e2a3a2afbfbe5b301a4977b1191fa4d03200c7880cdba10cad88f"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.2", "1.20.3", "1.20.4"]
