name = "Optim"
author = "darksaid98"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88cabfe9bea49dee7e63e5a3dac94052f4d1546ca64bba49ebafebdf1073117d"

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.2", "1.20.3", "1.20.4"]
