name = "Optim"
author = "darksaid98"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed02c981486d264655e5349e03b223ce2e2b88a788430d1c764bc7b4331f8ec4"

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.2", "1.20.3", "1.20.4"]
