name = "Optim"
author = "darksaid98"
version = "v1.9.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f0e2511ad3a5d7d21229383794ec461443598b0acb15d360cd339e2bb3aef17"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"

[options]
acceptable-game-versions = ["1.21"]
