name = "Optim"
author = "darksaid98"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6535059047dbcbfbeb47bacf0f194923d08e8c00e56577e29ecd17a0b6f3f3b"

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.2", "1.20.3", "1.20.4"]
