name = "Optim"
author = "darksaid98"
version = "1.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80a9521fd733213e6861402ea28543b510cf76b862079dead85164cc33ca5822"

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.2", "1.20.3", "1.20.4"]
