name = "Optim"
author = "darksaid98"
version = "1.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2524b53d2e7d8925b9e5d8d085e06f8444809123319db4a695bb80e88c76cbf"

[versions]
fabric = "0.15.6"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.2", "1.20.3", "1.20.4"]
