name = "Optim"
author = "darksaid98"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "084165dc2abd565213c444410be0d9b618ca01f902b9c26872921d5ae16d5fdf"

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.2", "1.20.3", "1.20.4"]
