name = "Optim"
author = "darksaid98"
version = "1.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6cf9d4f676e0a7cd461aa88bfb8c8951008df7a61cdab0d95d18203f9dbf5fb"

[versions]
fabric = "0.15.6"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.2", "1.20.3", "1.20.4"]
