name = "Optim"
author = "darksaid98"
version = "1.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1dc6257e844fd9161f0ce54fcf2e5630e438215633efd55b3249234dc9e0cc4"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.2", "1.20.3", "1.20.4"]
