name = "Optim"
author = "darksaid98"
version = "v1.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03d232a0964d91b610557b1c42da859b6e576963077be1c75b77237fb42b23ef"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"

[options]
acceptable-game-versions = ["1.21"]
