name = "Optim"
author = "darksaid98"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51a5c1cebeb24451305a33ad04c508ee38b5bfc55856bbfde36198200a775a21"

[versions]
fabric = "0.15.6"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.2", "1.20.3", "1.20.4"]
