name = "Optim"
author = "darksaid98"
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90e75a68916e2125d0e8d1f3703b463458865ccb548f2e73f92bebe1ad14713f"

[versions]
fabric = "0.15.9"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.2", "1.20.3", "1.20.4"]
