name: 'Update config version fields'
description: 'Sets the version fields in all relevant modpack config files'

inputs:
  version:
    description: 'Modpack version'
    required: true
    default: '1.0.0'

runs:
  using: 'composite'
  steps:
    # Update version fields for client pack
    - name: Update client versions
      uses: colathro/toml-editor@1.1.0
      with:
        file: "./main/pack.toml"
        key: "version"
        value: "client-beta-v${{ inputs.version }}"